swagger: "2.0"
info:
  description: Swagger Definition for Recipes
  version: "1.0.0"
  title: Swagger Definition for Recipes
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /recipes:
    get:
      operationId: recipe.get_all
      tags:
        - Recipe
      summary: Get all the recipes
      description: Get all the recipes
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of recipes to get
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering recipes
          required: false
      responses:
        200:
          description: Successfully get recipes
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                recipe_id:
                  type: integer
                timestamp:
                  type: string
                ingredients:
                  type: array
                  items:
                    properties:
                      ingredient_id:
                        type: integer
                        description: Id of the ingredient
                      content:
                        type: string
                        description: ingredient description
                      timestamp:
                        type: string
                        description: Create/Update timestamp of this ingredient

    post:
      operationId: recipe.create
      tags:
        - Recipe
      summary: Create a recipe and add it to the recipe list
      description: Create a new recipe in the recipe list
      parameters:
        - name: recipe
          in: body
          description: recipe to create
          required: True
          schema:
            type: object
            properties:
              recipe_id:
                type: integer
                description: Id of the recipe
              title:
                type: string
                description: Title of the recipe
              ingredients:
                type: array
                items:
                  properties:
                    ingredient_id:
                      type: integer
                      description: Id of the ingredient
                    content:
                      type: string
                      description: ingredient description
                    timestamp:
                      type: string
                      description: Create/Update timestamp of this ingredient
      responses:
        201:
          description: Successfully created a recipe

  /recipes/{recipe_id}:
    get:
      operationId: recipe.get_one
      tags:
        - Recipe
      summary: Get a recipe
      description: Get a recipe
      parameters:
        - name: recipe_id
          in: path
          description: Id of the recipe to retrieve
          type: integer
          required: True
      responses:
        200:
          description: Successfully get a recipe for a given id
          schema:
            properties:
              recipe_id:
                type: integer
              title:
                type: string
              ingredients:
                type: array
                items:
                  properties:
                    ingredient_id:
                      type: integer
                      description: Id of the ingredient
                    content:
                      type: string
                      description: ingredient description
                    timestamp:
                      type: string
                      description: Create/Update timestamp of this ingredient

    put:
      operationId: recipe.update
      tags:
        - Recipe
      summary: Update a recipe
      description: Update a recipe
      parameters:
        - name: recipe_id
          in: path
          description: Id of the recipe to update
          type: integer
          required: True
        - name: recipe
          in: body
          schema:
            type: object
            properties:
              recipe_id:
                type: integer
              title:
                type: string
      responses:
        200:
          description: Successfully updated a recipe

    delete:
      operationId: recipe.delete
      tags:
        - Recipe
      summary: Delete a recipe
      description: Delete a recipe
      parameters:
        - name: recipe_id
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a recipe
    
  /recipes/{recipe_id}/ingredients:
    get:
      operationId: ingredient.get_ingredients_by_recipe
      tags:
        - Ingredients
      summary: Get all the ingredients for a recipe
      description: Get all the ingredients for a recipe
      parameters:
        - name: recipe_id
          in: path
          type: integer
          required: True
        - name: length
          in: query
          type: integer
          description: Number of ingredients to get
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering ingredients
          required: false
      responses:
        200:
          description: Successfully get ingredients for the recipe
          schema:
            type: array
            items:
              properties:
                content:
                  type: string
                ingredient_id:
                  type: string
                timestamp:
                  type: string

  /recipes/{recipe_id}/ingredients/{ingredient_id}:
    delete:
      operationId: ingredient.delete
      tags:
        - Ingredients
      summary: Delete an ingredient
      description: Delete an ingredient
      parameters:
        - name: recipe_id
          in: path
          type: integer
          required: True
        - name: ingredient_id
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a recipe

